apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: jaeger
    orgId: 1
  - name: chronowave
    orgId: 1

datasources:
  - name: jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
  - name: chronowave
    type: chronowave-grafana
    uid: chronowave-grafana
    url: http://jaeger:9668
    editable: false
